# Using an Official Node.js image as the base image

FROM node:18

# Settimg the work directory in the container

WORKDIR \Users\IfennaEkwenem\my-app

#Copy Package.Json

COPY package* .json ./

#Install the porject dependencies
RUN npm Install

#Application Code 
COPY 




